name: rss_feed
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  webfeed: ^0.4.2
  flutter_html: ^0.11.1
  shared_preferences: 0.5.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
